server:
  port: 8002
  
spring:
  application:
    name: user-service
  rabbitmq:
    host: 192.168.64.5
    port: 5672
    username: admin
    password: admin
    
sp:
  user-service:
    users: "[{\"id\":99,\"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"}]"

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
management:
  endpoints:
    web:
      exposure:
        include:
        - refresh